apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: primary-

patches:
  - patch: |
      - op: replace
        path: /spec/running
        value: true
    target:
      kind: VirtualMachine
resources:
  - path: datavolume.yaml

